name: ETL
on: 
  schedule:
   - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  get_time:
    uses: ./.github/workflows/etl_get_time.yml
  update_package_names:
    needs: get_time
    uses: ./.github/workflows/etl_update_package_names.yml
  update_latest_json:
    name: Update Latest Json
    needs: update_package_names
    uses: ./.github/workflows/etl_parallel.yml
    with: 
      split_cnt: 20
      branch_title: update_latest
      max-parallel: 20
      package-install-command: |
        pip install requests==2.28.2
        pip install tqdm
        pip install cryptography
      main-python-file: update_latest_all.py
      input-menu-file: data/package.menu
      git-add-command: git add data/latest/ etag/latest/
    secrets:
      pat: ${{ secrets.PERSONAL_TOKEN }}
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  list_latest_json:
    name: List the Downloaded Latest Json(s)
    needs: update_latest_json
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: build_menu
        run: |
          rm -f data/latest.menu
          ls data/latest/ | grep .json >> data/latest.menu
      - name: Git commit
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/latest.menu
          git diff-index --quiet HEAD || git commit -m 'update: latest menu'
      - name: Git pull
        run: |
          git config --global user.email "jeffrey82221@gmail.com"
          git config --global user.name "jeffrey82221"
          git config pull.rebase false
          git pull origin main || echo 'pull failed'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: main
  update_release_time:
    name: Do Release Time Table ETL
    needs: list_latest_json
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install package
        run: |
          pip install tqdm
          pip install pandas==1.4.2
          pip install pyarrow==8.0.0
          pip install toolz
      - name: RUN ETL
        run: |
          python update_release_time.py
      - name: Git commit
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/release_time
          git diff-index --quiet HEAD || git commit -m 'update: release time table'
      - name: Git pull
        run: |
          git config --global user.email "jeffrey82221@gmail.com"
          git config --global user.name "jeffrey82221"
          git config --global http.postBuffer 1048576000
          git config pull.rebase false
          git pull origin main || echo 'pull failed'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: main
  update_repo_info:
    name: Update Repo Info Json
    needs: list_latest_json
    uses: ./.github/workflows/etl_parallel.yml
    with: 
      split_cnt: 50
      branch_title: update_repo_info
      max-parallel: 5
      package-install-command: |
        pip install requests==2.28.2
        pip install tqdm
        pip install pypistats==1.1.0
        pip install toolz
        pip install cytoolz==0.12.1
        pip install httpx==0.23.0
      main-python-file: update_repo_info_all.py
      input-menu-file: data/latest.menu
      git-add-command: git add data/fork data/repo data/star data/watcher etag/
    secrets:
      pat: ${{ secrets.PERSONAL_TOKEN }}
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  merge_repo_infos:
    name: Merge Infos 
    needs: update_repo_info
    runs-on: ubuntu-latest
    strategy:
      matrix:
        split_cnt: [50]
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: Download Jsonls
        uses: actions/download-artifact@v3
        with:
          path: download
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: download
      - name: Merge jsonl
        run: |
          rm -f data/repo_info.jsonl
          end=$((${{ matrix.split_cnt }}-1))
          echo "end=$end"
          cat download/{0..end}/info.jsonl >> data/repo_info.jsonl
      - name: Git commit
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/repo_info.jsonl
          git diff-index --quiet HEAD || git commit -m 'update: email content'
      - name: Git pull
        run: |
          git config --global user.email "jeffrey82221@gmail.com"
          git config --global user.name "jeffrey82221"
          git config pull.rebase false
          git pull origin main || echo 'pull failed'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: main
