name: ETL
on: 
  schedule:
   - cron: "0 0 2 * *"
  workflow_dispatch:
jobs:
  get_time:
    uses: ./.github/workflows/etl_get_time.yml
  update_package_names:
    uses: ./.github/workflows/etl_single.yml
    with:
      main-python-file: update_package_names.py
      result-path: data/package.menu
    secrets:
      pat: ${{ secrets.PERSONAL_TOKEN }}
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      user-name: jeffrey82221
      user-email: jeffrey82221@gmail.com
  update_latest_json:
    name: Update Latest Json
    needs: [update_package_names, get_time]
    uses: ./.github/workflows/etl_parallel.yml
    with: 
      split_cnt: 20
      branch_title: update_latest
      max-parallel: 20
      main-python-file: update_latest_all.py
      input-menu-file: data/package.menu
      git-add-command: git add data/latest/ etag/latest/
      passing-tmp-file: false
      result-path: data/latest.menu
      result-merge-command: ls data/latest/ | grep .json >> data/latest.menu
      fast-debug: false
    secrets:
      pat: ${{ secrets.PERSONAL_TOKEN }}
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      user-name: jeffrey82221
      user-email: jeffrey82221@gmail.com
  update_repo_info:
    name: Update Repo Info Json
    needs: [update_latest_json, get_time]
    uses: ./.github/workflows/etl_parallel.yml
    with: 
      split_cnt: 50
      branch_title: update_repo_info
      max-parallel: 5
      main-python-file: update_repo_info_all.py
      input-menu-file: data/latest.menu
      git-add-command: git add data/fork data/repo data/star data/watcher etag/
      passing-tmp-file: true
      tmp-upload-path: /tmp/info.jsonl
      result-path: data/repo_info.jsonl
      result-merge-command: >-
        echo "CNT=$CNT";
        for ((i=0; i<$CNT; i++)); 
        do
           echo "i: ${i} \n";
           ls "./download/$i" || echo "./download/$i not found";
           cat "./download/$i/info.jsonl" >> "./data/repo_info.jsonl";
        done
      fast-debug: false
    secrets:
      pat: ${{ secrets.PERSONAL_TOKEN }}
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      user-name: jeffrey82221
      user-email: jeffrey82221@gmail.com
  update_release_time:
    needs: update_latest_json
    uses: ./.github/workflows/etl_single.yml
    with:
      main-python-file: update_release_time.py
      result-path: data/release_time
    secrets:
      pat: ${{ secrets.PERSONAL_TOKEN }}
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      user-name: jeffrey82221
      user-email: jeffrey82221@gmail.com
  check_schema:
    needs: [update_repo_info, update_latest_json, update_package_names]
    uses: ./.github/workflows/check.yml
    secrets:
      pat: ${{ secrets.PERSONAL_TOKEN }}
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      user-name: jeffrey82221
      user-email: jeffrey82221@gmail.com
