name: ETL
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update_package_names:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: Set Up Python 
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install package
        run: |
          pip install beautifulsoup4==4.12.0
          pip install requests==2.28.2
      - name: Run update script
        run : |
         ls
         python update_package_names.py
      - name: Git Commit 
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data
          git diff-index --quiet HEAD || git commit -m 'update: package names'
      - name: Git pull
        run: | 
          git config --global user.email "jeffrey82221@gmail.com"
          git config --global user.name "jeffrey82221"
          git config --global http.postBuffer 1048576000
          git config pull.rebase false
          git pull origin main || echo 'pull failed'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: main
  update_latest_jsons:
    name: Update Latest Json(s)
    needs: update_package_names
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        alpha: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
        split_cnt: [20]
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: Set Up Python 
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Run install
        run: |
          pip install requests==2.28.2
          pip install tqdm
          pip install cryptography
      - name: Try Delete
        run: git push origin -d update_latest/${{ matrix.alpha }} || echo 'do nothing'
      - name: New Branch
        run: |
          git config --global http.postBuffer 1048576000
          git checkout -b update_latest/${{ matrix.alpha }}
          git push --set-upstream origin update_latest/${{ matrix.alpha }}
      - name: Run update script
        run: python update_latest_all.py data/package.menu ${{ matrix.alpha }} ${{ matrix.split_cnt }}
      - name: Git Commit - Jsons
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/latest/
          git diff-index --quiet HEAD || git commit -m 'update: package latest json'
      - name: Push - Jsons
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: update_latest/${{ matrix.alpha }}
      - name: Pull Request - Jsons
        id: pr_jsons
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Merge update_latest/${{ matrix.alpha }}"
          token: ${{ secrets.PERSONAL_TOKEN }}
          branch: update_latest/${{ matrix.alpha }}
          base: main
          delete-branch: true
          labels: "automerge"
      - name: Merge Pull Request - Jsons
        if: steps.pr_jsons.outputs.pull-request-operation == 'created'
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.PERSONAL_TOKEN }}"
          MERGE_LABELS: "automerge"
          MERGE_METHOD: "rebase"
          MERGE_COMMIT_MESSAGE: "Automerge Latest Jsons ${{ matrix.alpha }}"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "${{ matrix.split_cnt }}"
          MERGE_DELETE_BRANCH: "true"
          MERGE_RETRY_SLEEP: "60000"
          MERGE_REQUIRED_APPROVALS: "0"
          PULL_REQUEST: "${{ steps.pr_jsons.outputs.pull-request-number }}"
  list_latest_json:
    name: List the Downloaded Latest Json(s)
    needs: update_latest_jsons
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: build_menu
        run: ls data/latest/ >> data/latest.menu
      - name: Git commit
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/latest.menu
          git diff-index --quiet HEAD || git commit -m 'update: latest menu'
      - name: Git pull
        run: |
          git config --global user.email "jeffrey82221@gmail.com"
          git config --global user.name "jeffrey82221"
          git config pull.rebase false
          git pull origin main || echo 'pull failed'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: main
  update_release_time:
    name: Do Release Time Table ETL
    needs: list_latest_json
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install package
        run: |
          pip install tqdm
          pip install pandas==1.4.2
          pip install pyarrow==8.0.0
      - name: RUN ETL
        run: |
          python update_release_time.py
      - name: Git commit
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/release_time
          git diff-index --quiet HEAD || git commit -m 'update: release time table'
      - name: Git pull
        run: |
          git config --global user.email "jeffrey82221@gmail.com"
          git config --global user.name "jeffrey82221"
          git config --global http.postBuffer 1048576000
          git config pull.rebase false
          git pull origin main || echo 'pull failed'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: main
  update_repo_info:
    name: Extract Repo Info and Download Count
    needs: update_latest_jsons
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        alpha: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
        split_cnt: [100]
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: Set Up Python 
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Run install
        run: |
          pip install requests==2.28.2
          pip install tqdm
          pip install pypistats==1.1.0
          pip install toolz
          pip install cytoolz==0.12.1
          pip install httpx==0.23.0
      - name: Run update script
        run: python update_repo_info_all.py data/latest.menu ${{ matrix.alpha }} ${{ matrix.split_cnt }}
      - name: Upload Tmp Jsonl
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.alpha }}"
          path: /tmp/info.jsonl
          retention-days: 1
  merge_repo_infos:
    name: Merge Jsonl into 
    needs: update_repo_info
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: Download Jsonls
        uses: actions/download-artifact@v3
        with:
          path: download
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: download
      - name: Merge jsonl
        run: |
          rm -f data/repo_info.jsonl
          cat download/{0..99}/info.jsonl >> data/repo_info.jsonl
      - name: Git commit
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/repo_info.jsonl
          git diff-index --quiet HEAD || git commit -m 'update: email content'
      - name: Git pull
        run: |
          git config --global user.email "jeffrey82221@gmail.com"
          git config --global user.name "jeffrey82221"
          git config pull.rebase false
          git pull origin main || echo 'pull failed'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: main

