name: ETL
on: 
  schedule:
   - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  get_time:
    uses: ./.github/workflows/etl_get_time.yml
  update_package_names:
    uses: ./.github/workflows/etl_single.yml
    with:
      package-install-command: |
        pip install beautifulsoup4==4.12.0
        pip install requests==2.28.2
      main-python-file: update_package_names.py
      result-path: data/package.menu
    secrets:
      pat: ${{ secrets.PERSONAL_TOKEN }}
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      user-name: jeffrey82221
      user-email: jeffrey82221@gmail.com
  update_latest_json:
    name: Update Latest Json
    needs: [update_package_names, get_time]
    uses: ./.github/workflows/etl_parallel.yml
    with: 
      split_cnt: 20
      branch_title: update_latest
      max-parallel: 20
      package-install-command: |
        pip install requests==2.28.2
        pip install tqdm
        pip install cryptography
      main-python-file: update_latest_all.py
      input-menu-file: data/package.menu
      git-add-command: git add data/latest/ etag/latest/
      passing-tmp-file: false
      result-path: data/latest.menu
      result-merge-command: ls data/latest/ | grep .json >> data/latest.menu
      fast-debug: true
    secrets:
      pat: ${{ secrets.PERSONAL_TOKEN }}
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      user-name: jeffrey82221
      user-email: jeffrey82221@gmail.com
  update_repo_info:
    name: Update Repo Info Json
    needs: [update_latest_json, get_time]
    uses: ./.github/workflows/etl_parallel.yml
    with: 
      split_cnt: 50
      branch_title: update_repo_info
      max-parallel: 5
      package-install-command: |
        pip install requests==2.28.2
        pip install tqdm
        pip install pypistats==1.1.0
        pip install toolz
        pip install cytoolz==0.12.1
        pip install httpx==0.23.0
      main-python-file: update_repo_info_all.py
      input-menu-file: data/latest.menu
      git-add-command: git add data/fork data/repo data/star data/watcher etag/
      passing-tmp-file: true
      tmp-upload-path: /tmp/info.jsonl
      result-path: data/repo_info.jsonl
      result-merge-command: |
        for ((i=0; i<n; i++));
          do 
            echo "i=$i";
            ls ./download/$i
            cat ./download/$i/info.jsonl >> data/repo_info.jsonl; 
          done
      fast-debug: true
    secrets:
      pat: ${{ secrets.PERSONAL_TOKEN }}
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      user-name: jeffrey82221
      user-email: jeffrey82221@gmail.com
  update_release_time:
    needs: update_latest_json
    uses: ./.github/workflows/etl_single.yml
    with:
      package-install-command: |
        pip install tqdm
        pip install pandas==1.4.2
        pip install pyarrow==8.0.0
        pip install toolz
      main-python-file: update_release_time.py
      result-path: data/release_time
    secrets:
      pat: ${{ secrets.PERSONAL_TOKEN }}
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      user-name: jeffrey82221
      user-email: jeffrey82221@gmail.com
