name: ETL
on: 
  schedule:
   - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  get_time:
    uses: ./.github/workflows/etl_get_time.yml
  experiment-parallel:
    name: Experiment with parallel ETL
    needs: get_time
    uses: ./.github/workflows/etl_parallel.yml
    with: 
      alpha: "[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]"
      split_cnt: 20
      branch_title: update_latest
      max-parallel: 20
      package-install-command: |
        pip install requests==2.28.2
        pip install tqdm
        pip install cryptography
      main-python-file: update_latest_all.py
      input-menu-file: data/package.menu
      upload-output-path: data/latest/
      git-add-command: git add data/latest/ etag/latest/
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  update_package_names:
    needs: experiment-parallel
    uses: ./.github/workflows/etl_update_package_names.yml
  update_latest_jsons:
    name: Update Latest Json(s)
    needs: [update_package_names, get_time, experiment-parallel]
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      max-parallel: 20
      matrix:
        alpha: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
        split_cnt: [20]
        branch_title: [update_latest]
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - name: Download current time
        uses: actions/download-artifact@v3
        with:
          name: "current-time"
          path: ./current-time
      - name: Use current time
        id: current-time
        run: echo "time=$(cat ./current-time/current-time.txt)" >> $GITHUB_OUTPUT
      - name: set branch name
        id: branch
        env: 
          BRANCH: "${{ matrix.branch_title }}/${{ steps.current-time.outputs.time }}-${{ matrix.alpha }}"
        run: |
          echo "$BRANCH"
          echo "name=$BRANCH" >> $GITHUB_OUTPUT
      - name: create new branch
        uses: peterjgrainger/action-create-branch@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          sha: '${{github.sha}}'
          branch: 'refs/heads/${{ steps.branch.outputs.name }}'
      - name: checkout feature branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: '${{ steps.branch.outputs.name }}'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: Set Up Python 
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Run install (@specific - before etl)
        run: |
          pip install requests==2.28.2
          pip install tqdm
          pip install cryptography
      - name: Run update script (@specific)
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 180
          command: python update_latest_all.py data/package.menu ${{ matrix.alpha }} ${{ matrix.split_cnt }}
      - name: Git Commit - Jsons (@specific commit-files)
        run: |
          rm -f /home/runner/work/PyPiMailCentor/PyPiMailCentor/.git/index.lock
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/latest/
          git add etag/latest/
          git diff-index --quiet HEAD || git commit -m '${{ matrix.branch_title}}: (${{ steps.current-time.outputs.time }}-${{ matrix.alpha }})'
      - name: Push - Jsons
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: '${{ steps.branch.outputs.name }}'
  merge_latest_branches:
    name: merge all feature branches onto main branch 
    needs: update_latest_jsons
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        branch_title: [update_latest]
        split_cnt: [20]
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - name: Download current time
        uses: actions/download-artifact@v3
        with:
          name: "current-time"
          path: ./current-time
      - name: Use current time
        id: current-time
        run: echo "time=$(cat ./current-time/current-time.txt)" >> $GITHUB_OUTPUT
      - name: set branch name
        id: branch
        env: 
          BRANCH: "${{ matrix.branch_title }}/${{ steps.current-time.outputs.time }}"
        run: |
          echo "$BRANCH"
          echo "name=$BRANCH" >> $GITHUB_OUTPUT
      - name: checkout main
        uses: actions/checkout@v3
        with:
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: fetch -> merge -> push
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          for ((i=0; i<${{ matrix.split_cnt }}; i++)); 
            do 
             git fetch origin ${{ steps.branch.outputs.name }}-$i;
             git switch ${{ steps.branch.outputs.name }}-$i;
             git switch main
             git pull origin main
             git merge ${{ steps.branch.outputs.name }}-$i --allow-unrelated-histories --strategy-option theirs
             git push origin main
          done
      - name: delete feature branches
        run: |
          for ((i=0; i<${{ matrix.split_cnt }}; i++));
            do
             git push origin --delete ${{ steps.branch.outputs.name }}-$i
          done
  list_latest_json:
    name: List the Downloaded Latest Json(s)
    needs: merge_latest_branches
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: build_menu
        run: |
          rm -f data/latest.menu
          ls data/latest/ | grep .json >> data/latest.menu
      - name: Git commit
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/latest.menu
          git diff-index --quiet HEAD || git commit -m 'update: latest menu'
      - name: Git pull
        run: |
          git config --global user.email "jeffrey82221@gmail.com"
          git config --global user.name "jeffrey82221"
          git config pull.rebase false
          git pull origin main || echo 'pull failed'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: main
  update_release_time:
    name: Do Release Time Table ETL
    needs: list_latest_json
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install package
        run: |
          pip install tqdm
          pip install pandas==1.4.2
          pip install pyarrow==8.0.0
          pip install toolz
      - name: RUN ETL
        run: |
          python update_release_time.py
      - name: Git commit
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/release_time
          git diff-index --quiet HEAD || git commit -m 'update: release time table'
      - name: Git pull
        run: |
          git config --global user.email "jeffrey82221@gmail.com"
          git config --global user.name "jeffrey82221"
          git config --global http.postBuffer 1048576000
          git config pull.rebase false
          git pull origin main || echo 'pull failed'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: main

