name: ETL
on: 
  schedule:
    - cron: "0 0 * * *"
jobs:
  update_package_names:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install package
        run: |
          pip install beautifulsoup4==4.12.0
          pip install requests==2.28.2
      - name: Run update script
        run : |
         ls
         python update_package_names.py
      - name: Git Commit 
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data
          git diff-index --quiet HEAD || git commit -m 'update: package names'
      - name: Git pull
        run: | 
          git config --global user.email "jeffrey82221@gmail.com"
          git config --global user.name "jeffrey82221"
          git config --global http.postBuffer 1048576000
          git config pull.rebase false
          git pull origin main || echo 'pull failed'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: main
  update_latest_json:
    name: Upload Latest Json(s)
    needs: update_package_names
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        alpha: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
        split_cnt: [20]
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Run install
        run: |
          pip install requests==2.28.2
          pip install tqdm
          pip install cryptography
      - name: Try Delete
        run: git push origin -d update_latest/${{ matrix.alpha }} || echo 'do nothing'
      - name: New Branch
        run: |
          git config --global http.postBuffer 1048576000
          git checkout -b update_latest/${{ matrix.alpha }}
          git push --set-upstream origin update_latest/${{ matrix.alpha }}
      - name: Run update script
        run: |
          cp data/latest.control /tmp/latest.control
          python update_latest_all.py ${{ matrix.alpha }} ${{ matrix.split_cnt }}
      - name: Git Commit - Jsons
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/latest/
          git add data/latest.control
          git diff-index --quiet HEAD || git commit -m 'update: package latest json'
      - name: Push - Jsons
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: update_latest/${{ matrix.alpha }}
      - name: Pull Request - Jsons
        id: pr_jsons
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Upload Latest Json(s) from update_latest/${{ matrix.alpha }}"
          token: ${{ secrets.PERSONAL_TOKEN }}
          branch: update_latest/${{ matrix.alpha }}
          base: main
          delete-branch: true
          labels: "automerge"
      - name: Merge Pull Request - Jsons
        if: steps.pr_jsons.outputs.pull-request-operation == 'created'
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.PERSONAL_TOKEN }}"
          MERGE_LABELS: "automerge"
          MERGE_METHOD: "rebase"
          MERGE_COMMIT_MESSAGE: "Automerge Latest Jsons ${{ matrix.alpha }}"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "${{ matrix.split_cnt }}"
          MERGE_DELETE_BRANCH: "true"
          MERGE_RETRY_SLEEP: "60000"
          MERGE_REQUIRED_APPROVALS: "0"
          PULL_REQUEST: "${{ steps.pr_jsons.outputs.pull-request-number }}"
      - name: 'Upload Control Table Change Log - append'
        uses: actions/upload-artifact@v3
        with:
          name: "append_${{ matrix.alpha }}"
          path: append.log
          retention-days: 1
      - name: 'Upload Control Table Change Log - delete'
        uses: actions/upload-artifact@v3
        with:
          name: "delete_${{ matrix.alpha }}"
          path: delete.log
          retention-days: 1
  apply_control_table_change:
    name: Apply Change to Control Table
    needs: update_latest_json
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Download Change Files
        uses: actions/download-artifact@v3
        with:
          path: control_change_log
      - name: Update Control Table
        run: python update_control_table.py 20 control_change_log data/latest.control
      - name: Git commit
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/latest.control
          git diff-index --quiet HEAD || git commit -m 'update: control table'
      - name: Git pull
        run: |
          git config --global user.email "jeffrey82221@gmail.com"
          git config --global user.name "jeffrey82221"
          git config --global http.postBuffer 1048576000
          git config pull.rebase false
          git pull origin main || echo 'pull failed'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: main
  update_release_time:
    name: Do Release Time Table ETL
    needs: apply_control_table_change
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install package
        run: |
          pip install tqdm
          pip install pandas==1.4.2
          pip install pyarrow==8.0.0
      - name: RUN ETL
        run: |
          python update_release_time.py
      - name: Git commit
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/release_time
          git diff-index --quiet HEAD || git commit -m 'update: release time table'
      - name: Git pull
        run: |
          git config --global user.email "jeffrey82221@gmail.com"
          git config --global user.name "jeffrey82221"
          git config --global http.postBuffer 1048576000
          git config pull.rebase false
          git pull origin main || echo 'pull failed'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: main     
