name: parallel
on:
  workflow_call:
    inputs:
      split_cnt:
        required: true
        type: number
      branch_title:
        required: true
        type: string
      max-parallel:
        required: true
        type: number
      package-install-command:
        required: true
        type: string
      main-python-file:
        required: true
        type: string
      input-menu-file:
        required: true
        type: string
      git-add-command:
        required: true
        type: string
      passing-tmp-file:
        required: false
        type: boolean
        default: false
      tmp-upload-path:
        required: false
        type: string
        default: /tmp/info.jsonl
      result-path:
        required: true
        type: string
      result-merge-command:
        required: true
        type: string
      fast-debug:
        required: false
        type: boolean
        default: false
      debug-cnt:
        required: false
        type: number
        default: 2
    secrets:
      pat:
        required: true
      ssh-private-key:
        required: true
      user-name:
        required: true
      user-email:
        required: true
jobs:
  make_range:
    name: Build Range
    runs-on: ubuntu-20.04
    outputs:
      range: ${{ steps.create_range.outputs.range }}
    steps:
      - name: create range
        id: create_range
        env: 
          FAST_DEBUG: "${{ inputs.fast-debug }}"
          LOOP_CNT: "${{ inputs.split_cnt }}"
          DEBUG_CNT: "${{ inputs.debug-cnt }}"
        run: |
          CONDITION=$FAST_DEBUG
          if $CONDITION; then
            n=$DEBUG_CNT
          else
            n=$LOOP_CNT
          fi
          echo "n=$n"
          string="["
          for ((i=0; i<n; i++)); do
            if [ $i -eq $((n-1)) ]; then
              string+="$i]"
            else
              string+="$i,"
            fi
          done
          echo $string
          echo "range=$string" >> $GITHUB_OUTPUT
  update:
    name: Run update
    needs: make_range
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      max-parallel: ${{ inputs.max-parallel }}
      matrix:
        alpha: ${{ fromJson(needs.make_range.outputs.range) }}
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - name: Download current time
        uses: actions/download-artifact@v3
        with:
          name: "current-time"
          path: ./current-time
      - name: Use current time
        id: current-time
        run: echo "time=$(cat ./current-time/current-time.txt)" >> $GITHUB_OUTPUT
      - name: set branch name
        id: branch
        env: 
          BRANCH: "${{ inputs.branch_title }}/${{ steps.current-time.outputs.time }}-${{ matrix.alpha }}"
        run: |
          echo "$BRANCH"
          echo "name=$BRANCH" >> $GITHUB_OUTPUT
      - name: create new branch
        uses: peterjgrainger/action-create-branch@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.pat }}
        with:
          sha: '${{github.sha}}'
          branch: 'refs/heads/${{ steps.branch.outputs.name }}'
      - name: checkout feature branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: '${{ steps.branch.outputs.name }}'
          ssh-key: ${{ secrets.ssh-private-key }}
          ssh-known-hosts: github.com
      - name: Set Up Python 
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Run install 
        run: ${{ inputs.package-install-command }}
      - name: Run update script (@specific)
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 180
          command: python ${{ inputs.main-python-file }} ${{ inputs.input-menu-file }} ${{ matrix.alpha }} ${{ inputs.split_cnt }}
      - name: Git Commit - Jsons (@specific commit-files)
        run: |
          rm -f /home/runner/work/PyPiMailCentor/PyPiMailCentor/.git/index.lock
          git config --global user.name "${{ secrets.user-name }}"
          git config --global user.email "${{ secrets.user-email }}"
          ${{ inputs.git-add-command }}
          git diff-index --quiet HEAD || git commit -m '${{ matrix.branch_title}}: (${{ steps.current-time.outputs.time }}-${{ matrix.alpha }})'
      - name: Push - Jsons
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.pat }}
          branch: '${{ steps.branch.outputs.name }}'
      - name: Upload Result
        if: ${{ inputs.passing-tmp-file }}
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.alpha }}"
          path: ${{ inputs.tmp-upload-path }}
          retention-days: 5
  merge_branches:
    name: merge all feature branches onto main branch 
    needs: update
    runs-on: ubuntu-20.04
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - name: Download current time
        uses: actions/download-artifact@v3
        with:
          name: "current-time"
          path: ./current-time
      - name: Use current time
        id: current-time
        run: echo "time=$(cat ./current-time/current-time.txt)" >> $GITHUB_OUTPUT
      - name: set branch name
        id: branch
        env: 
          BRANCH: "${{ inputs.branch_title }}/${{ steps.current-time.outputs.time }}"
        run: |
          echo "$BRANCH"
          echo "name=$BRANCH" >> $GITHUB_OUTPUT
      - name: checkout main
        uses: actions/checkout@v3
        with:
          ref: 'main'
          ssh-key: ${{ secrets.ssh-private-key }}
          ssh-known-hosts: github.com
      - name: fetch -> merge -> push
        env: 
          FAST_DEBUG: "${{ inputs.fast-debug }}"
          LOOP_CNT: "${{ inputs.split_cnt }}"
          DEBUG_CNT: "${{ inputs.debug-cnt }}"
        run: |
          git config --global user.name "${{ secrets.user-name }}"
          git config --global user.email "${{ secrets.user-email }}"
          CONDITION=$FAST_DEBUG
          if $CONDITION; then
            n=$DEBUG_CNT
          else
            n=$LOOP_CNT
          fi
          echo "n=$n"
          for ((i=0; i<n; i++)); 
            do 
             git fetch origin ${{ steps.branch.outputs.name }}-$i;
             git switch ${{ steps.branch.outputs.name }}-$i;
             git switch main
             git pull origin main
             git merge ${{ steps.branch.outputs.name }}-$i --allow-unrelated-histories --strategy-option theirs
             git push origin main
          done
      - name: delete feature branches
        env: 
          FAST_DEBUG: "${{ inputs.fast-debug }}"
          LOOP_CNT: "${{ inputs.split_cnt }}"
          DEBUG_CNT: "${{ inputs.debug-cnt }}"
        run: |
          CONDITION=$FAST_DEBUG
          if $CONDITION; then
            n=$DEBUG_CNT
          else
            n=$LOOP_CNT
          fi
          echo "n=$n"
          for ((i=0; i<n; i++));
            do
             git push origin --delete ${{ steps.branch.outputs.name }}-$i
          done
  merge_tmp_as_result:
    name: Merge Tmp Files into Result File 
    needs: merge_branches
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: Download Tmp Files
        if: ${{ inputs.passing-tmp-file }}
        uses: actions/download-artifact@v3
        with:
          path: download
      - name: Display structure of downloaded files
        if: ${{ inputs.passing-tmp-file }}
        run: ls -R
        working-directory: download
      - name: Merge jsonl
        env: 
          FAST_DEBUG: "${{ inputs.fast-debug }}"
          LOOP_CNT: "${{ inputs.split_cnt }}"
          DEBUG_CNT: "${{ inputs.debug-cnt }}"
        run: |
          CONDITION=$FAST_DEBUG
          if $CONDITION; then
            n=$DEBUG_CNT
          else
            n=$LOOP_CNT
          fi
          echo "n=$n"
          end=$(($n-1))
          echo "end=$end"
          rm -f ${{ inputs.result-path }}
          ${{ inputs.result-merge-command }} >> ${{ inputs.result-path }}
      - name: Git commit
        run: |
          git config --global user.name "${{ secrets.user-name }}"
          git config --global user.email "${{ secrets.user-email }}"
          git add ${{ inputs.result-path }}
          git diff-index --quiet HEAD || git commit -m 'result: ${{ inputs.result-path }}'
      - name: Git pull
        run: |
          git config pull.rebase false
          git pull origin main || echo 'pull failed'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.pat }}
          branch: main
