name: init_time
on:
  workflow_call:
jobs:
  get_time:
    name: Get execution time
    runs-on: ubuntu-20.04
    steps:
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD-HH
          utcOffset: "+08:00"
      - name: write current time to file
        env:
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
        run: echo $F_TIME >> ./current-time.txt
      - name: Debug bash
        run: >-
          echo "CNT=$CNT"
          for ((i=0; i<$CNT; i++)); 
          do
             echo "i: ${i} \n";
             ls "./download/$i" || echo "./download/$i not found";
             cat "./download/$i/info.jsonl" >> "./data/repo_info.jsonl" || echo "./download/$i/info.jsonl not found";
          done
        env:
          CNT: 3
      - name: Upload current time
        uses: actions/upload-artifact@v3
        with:
          name: "current-time"
          path: ./current-time.txt
          retention-days: ${{ inputs.retention-days }}
