name: Update Release Time
on:
  workflow_call:
jobs:
  update:
    name: Do Release Time Table ETL
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install package
        run: |
          pip install tqdm
          pip install pandas==1.4.2
          pip install pyarrow==8.0.0
          pip install toolz
      - name: RUN ETL
        run: |
          python update_release_time.py
      - name: Git commit
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/release_time
          git diff-index --quiet HEAD || git commit -m 'update: release time table'
      - name: Git pull
        run: |
          git config --global user.email "jeffrey82221@gmail.com"
          git config --global user.name "jeffrey82221"
          git config --global http.postBuffer 1048576000
          git config pull.rebase false
          git pull origin main || echo 'pull failed'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: main
