name: single
on:
  workflow_call:
    inputs:
      main-python-file:
        required: true
        type: string
      result-path:
        required: true
        type: string
    secrets:
      pat:
        required: true
      ssh-private-key:
        required: true
      user-name:
        required: true
      user-email:
        required: true
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.ssh-private-key }}
          ssh-known-hosts: github.com
      - name: Set Up Python 
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install package
        run: pip install -r requirements.txt
      - name: Run update script
        run : |
         python ${{ inputs.main-python-file }}
      - name: Git Commit 
        run: |
          git config --global user.name "${{ secrets.user-name }}"
          git config --global user.email "${{ secrets.user-email }}"
          git add ${{ inputs.result-path }}
          git diff-index --quiet HEAD || git commit -m 'update: ${{ inputs.result-path }}'
      - name: Git pull
        run: | 
          git config --global user.name "${{ secrets.user-name }}"
          git config --global user.email "${{ secrets.user-email }}"
          git config --global http.postBuffer 1048576000
          git config pull.rebase false
          git pull origin main || echo 'pull failed'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.pat }}
          branch: main
