name: REPO ETL
on: push
  #schedule:
   #- cron: "0 11 * * SUN"
jobs:
  update_repo_info:
    name: Update Repo Info
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 10
      matrix:
        alpha: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
        split_cnt: [100]
    steps:
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+08:00"
      - name: Use current time
        env:
          #TIME: "${{ steps.current-time.outputs.time }}"
          #R_TIME: "${{ steps.current-time.outputs.readableTime }}"
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
          #YEAR: "${{ steps.current-time.outputs.year }}"
          #DAY: "${{ steps.current-time.outputs.day }}"
        run: echo $F_TIME
      #- name: delete branch
        #run: curl -s -X DELETE -u jeffrey82221:${{secrets.PERSONAL_TOKEN}} https://api.github.com/repos/jeffrey82221/PyPiMailCentor/git/refs/heads/update_repo_info/${{ matrix.alpha }}
      - name: checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: Set Up Python 
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Run install
        run: |
          pip install requests==2.28.2
          pip install tqdm
          pip install pypistats==1.1.0
          pip install toolz
          pip install cytoolz==0.12.1
          pip install httpx==0.23.0
      - name: Wait
        uses: 1itachi/sleep-random@v1.0.0
        with:
          minutes: '10'
          random: 'true'
      - name: New Branch
        uses: nick-fields/retry@v2
        with:
          retry_wait_seconds: 1800
          max_attempts: 5
          retry_on: any
          timeout_seconds: 1800
          command: |
            git checkout -b update_repo_info/${{ steps.current-time.outputs.formattedTime }}-${{ matrix.alpha }} || echo 'cannot check new branch locally'
            git push --set-upstream origin update_repo_info/${{ steps.current-time.outputs.formattedTime }}-${{ matrix.alpha }}
      - name: Insert PAT
        run: echo ${{ secrets.PERSONAL_TOKEN }} >> pat.key
      - name: Run update script
        run: python update_repo_info_all.py data/latest.menu ${{ matrix.alpha }} ${{ matrix.split_cnt }}
      - name: Upload Tmp Jsonl
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.alpha }}"
          path: /tmp/info.jsonl
          retention-days: 1
      - name: Git Commit - Jsons
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/fork
          git add data/repo
          git add data/star
          git add data/watcher
          git add etag/
          git diff-index --quiet HEAD || git commit -m 'update: github api etag and response'
      - name: Push - Jsons
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: update_repo_info/${{ steps.current-time.outputs.formattedTime }}-${{ matrix.alpha }}
      - name: Pull Request - Jsons
        id: pr_jsons
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Merge update_repo_info/${{ steps.current-time.outputs.formattedTime }}-${{ matrix.alpha }}"
          token: ${{ secrets.PERSONAL_TOKEN }}
          branch: update_repo_info/${{ steps.current-time.outputs.formattedTime }}-${{ matrix.alpha }}
          base: main
          delete-branch: true
          labels: "automerge"
      - name: Merge Pull Request - Jsons
        if: steps.pr_jsons.outputs.pull-request-operation == 'created'
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.PERSONAL_TOKEN }}"
          MERGE_LABELS: "automerge"
          MERGE_METHOD: "rebase"
          MERGE_COMMIT_MESSAGE: "Automerge Repo Jsons ${{ matrix.alpha }}"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "${{ matrix.split_cnt }}"
          MERGE_DELETE_BRANCH: "true"
          MERGE_RETRY_SLEEP: "60000"
          MERGE_REQUIRED_APPROVALS: "0"
          PULL_REQUEST: "${{ steps.pr_jsons.outputs.pull-request-number }}"
  merge_repo_infos:
    name: Merge Infos 
    needs: update_repo_info
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: Download Jsonls
        uses: actions/download-artifact@v3
        with:
          path: download
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: download
      - name: Merge jsonl
        run: |
          rm -f data/repo_info.jsonl
          cat download/{0..99}/info.jsonl >> data/repo_info.jsonl
      - name: Git commit
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/repo_info.jsonl
          git diff-index --quiet HEAD || git commit -m 'update: email content'
      - name: Git pull
        run: |
          git config --global user.email "jeffrey82221@gmail.com"
          git config --global user.name "jeffrey82221"
          git config pull.rebase false
          git pull origin main || echo 'pull failed'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: main

