name: UpdateInfo
on: push
jobs:
  update_info:
    name: Extract Info and Update Download Count
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        alpha: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
        split_cnt: [20]
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Run install
        run: |
          pip install requests==2.28.2
          pip install tqdm
          pip install pypistats
      - name: Run update script
        run: python update_info_all.py data/latest.menu ${{ matrix.alpha }} ${{ matrix.split_cnt }}