name: UpdateInfo
on: 
  schedule:
    - cron: "0 8 * * *"
jobs:
  update_info:
    name: Extract Info and Update Download Count
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        alpha: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
        split_cnt: [100]
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Run install
        run: |
          pip install requests==2.28.2
          pip install tqdm
          pip install pypistats==1.1.0
          pip install toolz
          pip install cytoolz==0.12.1
          pip install httpx==0.23.0
      - name: Run update script
        run: python update_info_all.py data/latest.menu ${{ matrix.alpha }} ${{ matrix.split_cnt }}
      - name: Upload Tmp Jsonl
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.alpha }}"
          path: /tmp/info.jsonl
          retention-days: 1
  merge_jsonl:
    name: Merge Jsonl into 
    needs: update_info
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: 'main'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: github.com
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Download Jsonls
        uses: actions/download-artifact@v3
        with:
          path: download
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: download
      - name: Display structure of current path
        run: ls -R
